# Generated by Django 3.2.6 on 2021-08-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_belt', models.TextField()),
                ('kata', models.TextField()),
                ('hits', models.TextField()),
                ('blocks', models.TextField()),
                ('sit_ups', models.PositiveSmallIntegerField()),
                ('push_ups', models.PositiveSmallIntegerField()),
                ('press', models.PositiveSmallIntegerField()),
                ('kumite', models.PositiveSmallIntegerField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karate.belt')),
            ],
        ),
    ]
