# Generated by Django 3.2.6 on 2021-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0002_belt_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='belt_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='photos/'),
        ),
        migrations.AddField(
            model_name='info',
            name='kata_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='photos/'),
        ),
        migrations.AddField(
            model_name='info',
            name='kyu',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='about_belt',
            field=models.TextField(null=True),
        ),
    ]
