# Generated by Django 3.2.6 on 2021-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0004_auto_20210825_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belt',
            options={'ordering': ['-kyu'], 'verbose_name': 'пояса', 'verbose_name_plural': 'пояса'},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['name'], 'verbose_name': 'словарь', 'verbose_name_plural': 'словарь'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'информация об экзамене', 'verbose_name_plural': 'информация об экзамене'},
        ),
        migrations.AlterField(
            model_name='belt',
            name='about_belt',
            field=models.TextField(null=True, verbose_name='значение пояса'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='color',
            field=models.TextField(verbose_name='пояс'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='kyu',
            field=models.CharField(max_length=3, null=True, verbose_name='кю'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=50, verbose_name='термин'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='translate',
            field=models.CharField(max_length=50, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='info',
            name='blocks',
            field=models.TextField(verbose_name='блоки'),
        ),
        migrations.AlterField(
            model_name='info',
            name='hits',
            field=models.TextField(verbose_name='удары'),
        ),
        migrations.AlterField(
            model_name='info',
            name='kata',
            field=models.TextField(verbose_name='ката'),
        ),
        migrations.AlterField(
            model_name='info',
            name='kumite',
            field=models.PositiveSmallIntegerField(verbose_name='кумитэ(поединок)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='press',
            field=models.PositiveSmallIntegerField(verbose_name='пресс'),
        ),
        migrations.AlterField(
            model_name='info',
            name='push_ups',
            field=models.PositiveSmallIntegerField(verbose_name='кол-во отжиманий'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sit_ups',
            field=models.PositiveSmallIntegerField(verbose_name='кол-во приседаний'),
        ),
    ]
